"""Generated by tools/train_anomaly.py — DO NOT EDIT BY HAND.

Logistic-regression weights for the edge anomaly detector.

  trained          : 2026-08-06
  simulated days   : 14
  samples          : 840 (168 anomalous, 672 normal)
  train accuracy   : 0.9587
  holdout accuracy : 0.9714
  holdout precision: 0.9474
  holdout recall   : 0.9000
  seed             : 20260806

*** THE TRAINING DATA IS SIMULATED. ***

These figures describe how separable a synthetic household distribution is.
They are NOT evidence of real-world accuracy, and nothing that displays a score
derived from these weights may imply otherwise. In deployment the model would
retrain on real logged history. See anomaly.model_provenance().
"""

# Order matches anomaly.FEATURE_NAMES exactly.
FEATURE_NAMES = ['hour_sin', 'hour_cos', 'occupancy', 'lux_norm', 'temp_norm', 'watts_norm', 'lights_on', 'hvac_on', 'presence_away']

WEIGHTS = [
    2.475876801581348,  # hour_sin
    1.315819472489733,  # hour_cos
    -3.775816537882598,  # occupancy
    -0.6461520047111257,  # lux_norm
    0.8605847180133985,  # temp_norm
    1.9159951954257775,  # watts_norm
    2.359467335549231,  # lights_on
    3.4780380332423,  # hvac_on
    2.0838059086975105,  # presence_away
]

BIAS = -1.9252832881662088

TRAIN_DAYS = 14
TRAIN_SAMPLES = 840
TRAIN_ACCURACY = 0.9587301587301588
HOLDOUT_ACCURACY = 0.9714285714285714
HOLDOUT_PRECISION = 0.9473684210526315
HOLDOUT_RECALL = 0.9
TRAINING_DATA_IS_SIMULATED = True
SEED = 20260806
